
title: Jekyll 
email: shafia@example.com
description: >- # this means to ignore newlines until "baseurl:"
 Jekyll is a static site generator that runs on the Ruby programming language. You may have heard of Jekyll or static site generators, but don’t know how or where to get started. 
 This guide is intended to be a complete tutorial, and require no additional resources to get you up and running with Jekyll.
baseurl: "/TestingSite" # the subpath of your site, e.g. /blog
url: "http://shafiashamsu.github.io/TestingSite" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


