
title: Jekyll 
email: shafia@example.com
description: >-
 Jekyll is a static site generator that runs on the Ruby programming language. You may have heard of Jekyll or static site generators, but don’t know how or where to get started. 
 This guide is intended to be a complete tutorial, and require no additional resources to get you up and running with Jekyll.
baseurl: "/TestingSite" 
url: "http://shafiashamsu.github.io/TestingSite" 


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


